#!/usr/bin/env node
// Interactive profile builder. Writes ~/.jobhunt-kit/profile.yml from your answers.
// No dependencies — uses only Node built-ins. Run: node wizard.mjs
// Works both interactively (a real terminal) and with piped input (for testing);
// on end-of-input any unanswered questions fall back to their defaults.
import { createInterface } from "node:readline";
import { stdin as input, stdout as output } from "node:process";
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const DEST_DIR = join(homedir(), ".jobhunt-kit");
const DEST = join(DEST_DIR, "profile.yml");

// ── line reader that works for TTY and piped stdin ─────────────────────────
const rl = createInterface({ input, output });
const queue = [];
const waiters = [];
let closed = false;
rl.on("line", (l) => { waiters.length ? waiters.shift()(l) : queue.push(l); });
rl.on("close", () => { closed = true; while (waiters.length) waiters.shift()(null); });
function nextLine() {
  return new Promise((resolve) => {
    if (queue.length) return resolve(queue.shift());
    if (closed) return resolve(null);
    waiters.push(resolve);
  });
}
async function ask(q, def = "") {
  output.write(`  ${q}${def ? ` [${def}]` : ""}: `);
  const a = await nextLine();
  if (a === null) { output.write("\n"); return def; }
  return a.trim() || def;
}
async function askYesNo(q, def = false) {
  const a = await ask(`${q} (y/n)`, def ? "y" : "n");
  return String(a).toLowerCase().startsWith("y");
}
const q = (s) => JSON.stringify(String(s ?? ""));

// ── interview ──────────────────────────────────────────────────────────────
output.write("\n═══ physician-jobhunt-kit — profile setup ═══\n");
if (existsSync(DEST)) {
  output.write(`\n  A profile already exists at ${DEST}\n`);
  if (!(await askYesNo("  Overwrite it?", false))) {
    output.write("  Keeping the existing profile. Edit it by hand any time.\n");
    rl.close(); process.exit(0);
  }
}

output.write("\n— About you —\n");
const name = await ask("Full name as it should appear in signatures", "Dr. Jane Smith, MD");
const first = await ask("First name (for the friendly sign-off)", name.split(" ")[1] || "Jane");
const email = await ask("Email you'll SEND from");
const alias = await ask("The google-mcp alias for that email (set during authentication)", "personal");
const phone = await ask("Cell phone (E.164, e.g. +15551234567)");
const cv = await ask("Absolute path to your CV PDF", `${homedir()}/Downloads/CV.pdf`);
const summary = await ask("One-line self-intro for recruiters (training + strengths)",
  "finishing residency in 2027, with hospital + outpatient experience");
const grad = await ask("Graduation (month year)", "June 2027");
const start = await ask("Target start (month year)", "August 2027");

output.write("\n— Visa —\n");
const visaReq = await askYesNo("Do you need visa sponsorship (IMG on a training visa)?", false);
let visaSit = "", visaTag = "";
if (visaReq) {
  visaSit = await ask("Describe your visa need", "J-1 visa — need a J-1 waiver + H-1B sponsorship");
  visaTag = await ask("Short subject-line tag", "(J-1 visa)");
}

output.write("\n— Criteria —\n");
const specialties = await ask("Your specialty/ies (comma-separated)", "Family Medicine");
const roles = await ask("Target roles (comma-separated)", "hospitalist, EM open to FM-trained");
const minComp = await ask("Minimum base comp (USD number)", "300000");
const geography = await ask("States to target (comma-separated, or 'any')", "any");
const welcome = await askYesNo("Run a community-welcome check before applying (recommended for IMGs/POC)?", true);

output.write("\n— Texting (optional, macOS) —\n");
const texting = await askYesNo("Enable the texting skill (draft/send iMessage in your voice)?", false);
let yourNum = "";
if (texting) yourNum = await ask("Your own cell for receipts (E.164)", phone);

// ── write ────────────────────────────────────────────────────────────────
const yaml = `# Generated by wizard.mjs — edit any field by hand any time.
identity:
  name: ${q(name)}
  first_name: ${q(first)}
  email: ${q(email)}
  send_alias: ${q(alias)}
  phone: ${q(phone)}
  cv_path: ${q(cv)}
  sign_off: |
    Thanks!
    ${first}

training:
  summary: ${q(summary)}
  graduation: ${q(grad)}
  target_start: ${q(start)}

visa:
  required: ${visaReq}
  situation: ${q(visaSit || "N/A")}
  subject_tag: ${q(visaTag || "")}

criteria:
  specialties: [${specialties.split(",").map((s) => q(s.trim())).join(", ")}]
  target_roles: [${roles.split(",").map((s) => q(s.trim())).join(", ")}]
  min_comp_usd: ${parseInt(minComp, 10) || 300000}
  outpatient_ok_above_usd: 350000
  new_grad_friendly: true
  no_locums: true
  geography: [${geography.split(",").map((s) => q(s.trim())).join(", ")}]
  climate: "mild-ish winters, ideally four seasons"
  lifestyle: "within ~1-2 hours of a city, good schools, safe, good place to raise a family"
  no_income_tax_states_preferred: true
  welcome_check: ${welcome}
  welcome_note: "I want somewhere my family is genuinely welcome and safe."

tracker:
  sheet_id: ""
  sheet_name: "Physician Job Search — Email Tracker"

texting:
  enabled: ${texting}
  your_number: ${q(yourNum)}
  contacts: {}
`;

mkdirSync(DEST_DIR, { recursive: true });
writeFileSync(DEST, yaml, "utf8");
output.write(`\n  ✓ Wrote ${DEST}\n`);
output.write("  You can edit it any time. The tracker sheet_id fills in on your first jobsearch run.\n\n");
rl.close();
